POST http://localhost:8080/transfers/create
Content-Type: application/x-www-form-urlencoded

address=Street&account=123456&title=Invoice12/345&sum=123&person=Jan&bankTransferIds=2
###
POST http://localhost:8080/transfers/delete
Content-Type: application/x-www-form-urlencoded


###
POST http://localhost:8080/transfers/update
Content-Type: application/x-www-form-urlencoded