GET http://localhost:8080/persons/get?id=5

###
POST http://localhost:8080/persons/create
Content-Type: application/x-www-form-urlencoded



###
POST http://localhost:8080/persons/delete
Content-Type: application/x-www-form-urlencoded



###
POST http://localhost:8080/persons/update
Content-Type: application/x-www-form-urlencoded

